export const eventsData = [
    {
        title: "Darpan",
        slug: "darpan",
        category: "Photography",
        image: "/images/event/1.jpg",
        description: "Enthusiastic Shutterbugs, it's your turn to grasp your camera and make your eyes act like a shutter and your mind like a lens. Capture what it actually feels like, not what it looks like.",
        rules: [
            "Theme: Open",
            "This is an individual competition.",
            "Any camera may be used (DSLR, Mobile, etc.).",
            "Each participant can submit up to 5 pictures.",
            "Photos must be submitted as a PDF with a title & brief description (max 30 words).",
            "Only basic editing (cropping, brightness, hue, contrast) is allowed.",
            "Mention your email ID and WhatsApp number.",
            "Plagiarism will not be entertained.",
            "Entries must have a 16:9 ratio.",
            "Failure to follow rules will lead to disqualification."
        ]
    },
    {
        title: "Reel Making",
        slug: "reel-making",
        category: "Videography",
        image: "/images/event/2.jpg",
        description: "Create engaging reels that tell a story in seconds.",
        rules: ["Time limit: 60 seconds", "Original content only"]
    },
    // ... (mapped for other events, simply adding slugs for now to prevent errors)
    { title: "Treasure Hunt", slug: "treasure-hunt", category: "Fun", image: "/images/event/3.jpg", description: "Hunt for clues across the campus.", rules: [] },
    { title: "Marketing Mania", slug: "marketing-mania", category: "Business", image: "/images/event/4.jpg", description: "Sell your ideas to the sharks.", rules: [] },
    { title: "Tasveeron ki dastan", slug: "picture-story", category: "Picture Story", image: "/images/event/5.jpg", description: "Weave a story through a series of pictures.", rules: [] },
    { title: "One to One Battle", slug: "dance-battle", category: "Dance", image: "/images/event/6.jpg", description: "Face off in an epic dance battle.", rules: [] },
    { title: "Roobaroo", slug: "debate", category: "Debate", image: "/images/event/7.jpg", description: "Voice your opinion.", rules: [] },
    { title: "Rangmanch", slug: "open-stage", category: "Open Stage", image: "/images/event/8.jpg", description: "The stage is yours.", rules: [] },
    { title: "Sargam", slug: "solo-singing", category: "Solo Singing", image: "/images/event/9.jpg", description: "Melodious solo performances.", rules: [] },
    { title: "Swarsangam", slug: "band-war", category: "Band War", image: "/images/event/10.jpg", description: "Battle of the bands.", rules: [] },
    { title: "Graffiti Extravanza", slug: "graffiti", category: "Art", image: "/images/event/11.jpg", description: "Paint the walls with your imagination.", rules: [] },
    { title: "Mukhauta", slug: "face-painting", category: "Face Painting", image: "/images/event/12.jpg", description: "Face painting competition.", rules: [] },
    { title: "Ekanki", slug: "monoact", category: "Monoact", image: "/images/event/13.jpg", description: "Solo theatrical performance.", rules: [] },
    { title: "T-Shirt Painting", slug: "tshirt-painting", category: "Art", image: "/images/event/14.jpg", description: "Design your own tee.", rules: [] },
    { title: "Tehkikat", slug: "case-study", category: "Case Study", image: "/images/event/15.jpg", description: "Solve real world problems.", rules: [] },
    { title: "Pratibimb", slug: "live-sketching", category: "Live Sketching", image: "/images/event/16.jpg", description: "Sketch live subjects.", rules: [] },
    { title: "Mr/Miss Encore", slug: "pageant", category: "Pageant", image: "/images/event/17.jpg", description: "The hunt for the face of Encore.", rules: [] },
    { title: "Rangsaaz", slug: "relay-rangoli", category: "Relay Rangoli", image: "/images/event/18.jpg", description: "Team rangoli competition.", rules: [] },
    { title: "Bawaal", slug: "nukkad", category: "Nukkad", image: "/images/event/19.jpg", description: "Street play competition.", rules: [] },
    { title: "Raftaar", slug: "rap-battle", category: "Rap Battle", image: "/images/event/20.jpg", description: "Rap battle.", rules: [] },
    { title: "Kirdaar", slug: "mimicry", category: "Mimicry", image: "/images/event/21.jpg", description: "Imitate and entertain.", rules: [] },
    { title: "Natraj", slug: "solo-dance", category: "Solo Dance", image: "/images/event/23.jpg", description: "Solo dance performance.", rules: [] },
    { title: "Safarnama", slug: "short-film", category: "Short Film", image: "/images/event/24.jpg", description: "Short film making.", rules: [] },
    { title: "Maya Bazaar", slug: "auction", category: "Auction", image: "/images/event/25.jpg", description: "IPL style auction.", rules: [] },
    { title: "Model United Nations", slug: "mun", category: "MUN", image: "/images/event/26.jpg", description: "Mock UN session.", rules: [] },
    { title: "Afsane", slug: "twist-a-tale", category: "Twist a Tale", image: "/images/event/27.jpg", description: "Story writing with a twist.", rules: [] },
    { title: "Rags", slug: "group-dance", category: "Group Dance", image: "/images/event/28.jpg", description: "Group dance competition.", rules: [] },
    { title: "Jumla", slug: "jam", category: "JAM", image: "/images/event/29.jpg", description: "Just a Minute.", rules: [] },
];
