export const eventsData = [
    {
        title: "Darpan",
        slug: "darpan",
        category: "Mirage (Solo)",
        price: 150,
        image: "/images/event/1.jpg",
        description: "Enthusiastic Shutterbugs, it's your turn to grasp your camera and make your eyes act like a shutter and your mind like a lens. Capture what it actually feels like, not what it looks like.",
        venue: "Kalam Hall / Centre stage / Auditorium / LT11",
        time: "All Day",
        rules: [
            "Theme: Open",
            "This is an individual competition.",
            "Any camera may be used (DSLR, Mobile, etc.).",
            "Each participant can submit up to 5 pictures.",
            "Photos must be submitted as a PDF with a title & brief description (max 30 words).",
            "Only basic editing (cropping, brightness, hue, contrast) is allowed.",
            "Entries must have a 16:9 ratio.",
            "Details: Mention your email ID and WhatsApp number.",
            "Failure to follow rules will lead to disqualification."
        ]
    },
    {
        title: "Reel Making",
        slug: "reel-making",
        category: "Mirage (Group)",
        price: 250,
        image: "/images/event/2.jpg",
        description: "Create engaging reels that tell a story in seconds.",
        venue: "Kalam Hall / Centre",
        time: "All Day",
        rules: ["Time limit: 60 seconds", "Original content only"],
        isTeam: true,
        minSize: 1,
        maxSize: 4
    },
    {
        title: "Natraj",
        slug: "solo-dance",
        category: "Dance (Solo)",
        price: 200,
        image: "/images/event/23.jpg",
        description: "Solo dance performance.",
        venue: "Arena / Secondary stage / Auditorium",
        time: "TBA",
        rules: []
    },
    {
        title: "Rhythm Rebels",
        slug: "duo-dance",
        category: "Dance (Duo)",
        price: 300,
        image: "/images/event/rhythm_rebels.jpg",
        description: "Duo dance competition.",
        venue: "Arena / Secondary stage / Auditorium",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 2,
        maxSize: 2
    },
    {
        title: "Raqs",
        slug: "group-dance",
        category: "Dance (Group)",
        price: 600, // Min 5 * 120
        image: "/images/event/28.jpg",
        description: "Group dance competition.",
        venue: "Main Stage",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 5,
        maxSize: 20
    },
    {
        title: "Relay Rangoli",
        slug: "relay-rangoli",
        category: "Art and Craft",
        price: 200, // 4 * 50
        image: "/images/event/18.jpg",
        description: "Team rangoli competition.",
        venue: "Auditorium",
        time: "Day-1, 10 AM",
        rules: [],
        isTeam: true,
        minSize: 4,
        maxSize: 4
    },
    {
        title: "Live Sketching",
        slug: "live-sketching",
        category: "Art and Craft",
        price: 100,
        image: "/images/event/16.jpg",
        description: "Sketch live subjects.",
        venue: "Arena / Garden",
        time: "Day-1, 10 AM",
        rules: []
    },
    {
        title: "Brush the Theme",
        slug: "brush-the-theme",
        category: "Art and Craft",
        price: 100,
        image: "/images/event/11.jpg",
        description: "Painting competition based on a theme.",
        venue: "Arena / Garden / LT",
        time: "Day-2, 10 AM",
        rules: []
    },
    {
        title: "Face Painting",
        slug: "face-painting",
        category: "Art and Craft",
        price: 100,
        image: "/images/event/12.jpg",
        description: "Face painting competition.",
        venue: "Arena / Garden",
        time: "Day-2, 2 PM",
        rules: []
    },
    {
        title: "Sargam",
        slug: "solo-singing",
        category: "Singing (Solo)",
        price: 150,
        image: "/images/event/9.jpg",
        description: "Melodious solo performances.",
        venue: "Secondary stage / arena",
        time: "TBA",
        rules: []
    },
    {
        title: "Raftaar",
        slug: "rap-battle",
        category: "Singing (Solo)",
        price: 150,
        image: "/images/event/20.jpg",
        description: "Rap battle.",
        venue: "Secondary stage / arena",
        time: "TBA",
        rules: []
    },
    {
        title: "Swarsangam",
        slug: "band-war",
        category: "Singing (Group)",
        price: 600, // Min 3 * 200
        image: "/images/event/10.jpg",
        description: "Battle of the bands.",
        venue: "Main Stage",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 3,
        maxSize: 8
    },
    {
        title: "Bawaal (Nukkad)",
        slug: "nukkad",
        category: "Dramatics (Group)",
        price: 1000,
        image: "/images/event/19.jpg",
        description: "Street play competition.",
        venue: "Arena",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 8,
        maxSize: 20
    },
    {
        title: "Ekanki (Monoact)",
        slug: "monoact",
        category: "Dramatics (Solo)",
        price: 250,
        image: "/images/event/13.jpg",
        description: "Solo theatrical performance.",
        venue: "Auditorium",
        time: "TBA",
        rules: []
    },
    {
        title: "Tamasha (Skit)",
        slug: "skit",
        category: "Dramatics (Group)",
        price: 500,
        image: "/images/event/skit.png",
        description: "Group skit performance.",
        venue: "Auditorium",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 3,
        maxSize: 10
    },
    {
        title: "Mime",
        slug: "mime",
        category: "Dramatics (Group/ Solo)",
        price: 400,
        image: "/images/event/mime.png",
        description: "Silent acting.",
        venue: "Auditorium",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 1,
        maxSize: 8
    },
    {
        title: "Kirdaar",
        slug: "mimicry",
        category: "Dramatics",
        price: 200,
        image: "/images/event/21.jpg",
        description: "Imitate and entertain.",
        venue: "Auditorium",
        time: "TBA",
        rules: []
    },
    {
        title: "Cosplay",
        slug: "cosplay",
        category: "Dramatics",
        price: 300,
        image: "/images/event/26.jpg",
        description: "Dress up as your favorite character.",
        venue: "Auditorium / arena",
        time: "TBA",
        rules: []
    },
    {
        title: "Marketing Mania",
        slug: "marketing-mania",
        category: "E-cell (Group)",
        price: 120, // 3 * 40
        image: "/images/event/4.jpg",
        description: "Sell your ideas to the sharks.",
        venue: "Kalam Hall/ Main stage/ Auditorium/ LT-11",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 3,
        maxSize: 5
    },
    {
        title: "Tehkikat",
        slug: "case-study",
        category: "E-cell (Group)",
        price: 100, // 2 * 50
        image: "/images/event/15.jpg",
        description: "Solve real world problems.",
        venue: "College campus",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 2,
        maxSize: 4
    },
    {
        title: "Startup Auction",
        slug: "startup-auction",
        category: "E-cell (Group)",
        price: 150, // 3* 50
        image: "/images/event/25.jpg",
        description: "IPL style auction for Startups.",
        venue: "Auditorium/ Main stage",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 3,
        maxSize: 5
    },
    {
        title: "Startup Conclave",
        slug: "startup-conclave",
        category: "E-cell (Group)",
        price: 0,
        image: "/images/event/4.jpg",
        description: "Networking and insights from industry leaders.",
        venue: "Auditorium",
        time: "TBA",
        rules: ["Entry free for participants registered in any other E-Cell event."]
    },
    {
        title: "Essay Writing",
        slug: "essay-writing",
        category: "Literary (Solo)",
        price: 100,
        image: "/images/event/essay-writing.jpg",
        description: "Pen down your thoughts.",
        venue: "Kalam Hall",
        time: "TBA",
        rules: []
    },
    {
        title: "Afsane (Twist a tale)",
        slug: "twist-a-tale",
        category: "Literary (Individual / pair)",
        price: 100,
        image: "/images/event/27.jpg",
        description: "Story writing with a twist.",
        venue: "Kalam Hall",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 1,
        maxSize: 2
    },
    {
        title: "Roobaroo (Debate)",
        slug: "debate",
        category: "Literary (Group)",
        price: 200, // 2 * 100 assumed group size
        image: "/images/event/7.jpg",
        description: "Voice your opinion.",
        venue: "Kalam Hall / Conference Hall",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 2,
        maxSize: 2
    },
    {
        title: "Jumla (JAM)",
        slug: "jam",
        category: "Literary (Solo)",
        price: 100,
        image: "/images/event/29.jpg",
        description: "Just a Minute.",
        venue: "Auditorium",
        time: "TBA",
        rules: []
    },
    {
        title: "Rangmanch (Open stage)",
        slug: "open-stage",
        category: "Literary (Solo/ Group)",
        price: 100,
        image: "/images/event/rangmanch.jpg",
        description: "The stage is yours.",
        venue: "Auditorium",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 1,
        maxSize: 5
    },
    {
        title: "Lit Quiz",
        slug: "lit-quiz",
        category: "Literary (Group)",
        price: 200, // 2 * 100
        image: "/images/event/lit-quiz.jpg",
        description: "Test your literary knowledge.",
        venue: "Kalam Hall",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 2,
        maxSize: 3
    },
    {
        title: "Open Stage Poetry",
        slug: "poetry",
        category: "Literary (Solo)",
        price: 100,
        image: "/images/event/poetry.png",
        description: "Express with verses.",
        venue: "Auditorium",
        time: "TBA",
        rules: []
    },
    {
        title: "Tasveeron Kee Dastan",
        slug: "picture-story",
        category: "Mirage (Solo)",
        price: 100,
        image: "/images/event/5.jpg",
        description: "Weave a story through a series of pictures.",
        venue: "Kalam Hall / Centre stage / Auditorium / LT11",
        time: "TBA",
        rules: []
    },
    {
        title: "Safarnama (Short Film)",
        slug: "short-film",
        category: "Mirage (Group)",
        price: 250,
        image: "/images/event/24.jpg",
        description: "Short film making.",
        venue: "Kalam Hall / Centre stage / Auditorium / LT11",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 2,
        maxSize: 10
    },
    {
        title: "Treasure Hunt",
        slug: "treasure-hunt",
        category: "Fun",
        price: 300,
        image: "/images/event/3.jpg",
        description: "Hunt for clues across the campus.",
        venue: "Campus",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 3,
        maxSize: 5
    },
    {
        title: "One to One Battle",
        slug: "dance-battle",
        category: "Dance",
        price: 250,
        image: "/images/event/6.jpg",
        description: "Face off in an epic dance battle.",
        venue: "Main Stage",
        time: "TBA",
        rules: []
    },
    {
        title: "Graffiti Extravanza",
        slug: "graffiti",
        category: "Art",
        price: 150,
        image: "/images/event/11.jpg",
        description: "Paint the walls with your imagination.",
        venue: "Wall Area",
        time: "TBA",
        rules: []
    },
    {
        title: "T-Shirt Painting",
        slug: "tshirt-painting",
        category: "Art",
        price: 200,
        image: "/images/event/14.jpg",
        description: "Design your own tee.",
        venue: "Garden",
        time: "TBA",
        rules: []
    },
    {
        title: "Mr/Miss Encore",
        slug: "pageant",
        category: "Pageant",
        price: 300,
        image: "/images/event/17.jpg",
        description: "The hunt for the face of Encore.",
        venue: "Main Stage",
        time: "TBA",
        rules: []
    },
    {
        title: "Model United Nations",
        slug: "mun",
        category: "MUN",
        price: 500,
        image: "/images/event/mun.png",
        description: "Mock UN session.",
        venue: "Conference Hall",
        time: "TBA",
        rules: [],
        isTeam: true,
        minSize: 1,
        maxSize: 2
    }
];
